//! Tools

use std::collections::BTreeSet;

use insim_core::object::{concrete::ConcreteSlab, ObjectCoordinate, ObjectInfo};

use crate::object_catalog::{ObjectCatalogKind, ObjectCategory, CATEGORY_ORDER};

/// ToolKind
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToolKind {
    /// Selection
    Select,
    /// Place
    Place,
    /// Spline Path
    SplinePath,
    /// Ramp Generator
    RampGen,
}

/// Selection tool state.
#[derive(Debug, Default)]
pub struct SelectState {
    /// Selected object IDs.
    pub selected_object_ids: Vec<u64>,
}

/// Placement tool state.
#[derive(Debug)]
pub struct PlaceState {
    /// Search query.
    pub search_query: String,
    /// Selected object type.
    pub selected_object_kind: ObjectCatalogKind,
    /// Expanded object library categories.
    pub open_categories: BTreeSet<ObjectCategory>,
}

impl Default for PlaceState {
    fn default() -> Self {
        Self {
            search_query: String::new(),
            selected_object_kind: ObjectCatalogKind::default(),
            open_categories: CATEGORY_ORDER.iter().copied().collect(),
        }
    }
}

/// Spline path tool state.
#[derive(Debug)]
pub struct SplinePathState {
    /// Spline control points in raw units.
    pub control_points: Vec<[i16; 2]>,
    /// Search query for object library.
    pub search_query: String,
    /// Selected object kind for generated objects.
    pub selected_object_kind: ObjectCatalogKind,
    /// Template object for generated spline placements.
    pub object_template: ObjectInfo,
    /// Expanded object library categories.
    pub open_categories: BTreeSet<ObjectCategory>,
    /// Object spacing in raw units.
    pub spacing_units: i32,
    /// IDs generated by last spline apply.
    pub generated_object_ids: Vec<u64>,
}

impl Default for SplinePathState {
    fn default() -> Self {
        Self {
            control_points: Vec::new(),
            search_query: String::new(),
            selected_object_kind: ObjectCatalogKind::default(),
            object_template: ObjectCatalogKind::default().create_default(),
            open_categories: CATEGORY_ORDER.iter().copied().collect(),
            spacing_units: 160,
            generated_object_ids: Vec::new(),
        }
    }
}

/// Ramp generator tool state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RampNode {
    /// X coordinate (raw units).
    pub x: i16,
    /// Y coordinate (raw units).
    pub y: i16,
    /// Z coordinate (raw units).
    pub z: u8,
}

/// Ramp generator tool state.
#[derive(Debug)]
pub struct RampGenState {
    /// Guide/control points.
    pub control_points: Vec<RampNode>,
    /// Selected guide point index.
    pub selected_node: Option<usize>,
    /// Template concrete object.
    pub object_template: ObjectInfo,
    /// Sampling steps per segment.
    pub steps_per_segment: usize,
    /// IDs generated by last ramp apply.
    pub generated_object_ids: Vec<u64>,
}

impl Default for RampGenState {
    fn default() -> Self {
        Self {
            control_points: Vec::new(),
            selected_node: None,
            object_template: ObjectInfo::ConcreteSlab(ConcreteSlab {
                xyz: ObjectCoordinate::default(),
                ..Default::default()
            }),
            steps_per_segment: 100,
            generated_object_ids: Vec::new(),
        }
    }
}

/// All editor tool state.
#[derive(Debug, Default)]
pub struct Tools {
    /// Active tool.
    pub active: ToolKind,
    /// Selection state.
    pub select: SelectState,
    /// Placement state.
    pub place: PlaceState,
    /// Spline path state.
    pub spline_path: SplinePathState,
    /// Ramp generator state.
    pub ramp_gen: RampGenState,
}

impl Tools {
    /// Activates a tool.
    pub fn activate(&mut self, kind: ToolKind) {
        self.active = kind;
    }
}

impl Default for ToolKind {
    fn default() -> Self {
        Self::Select
    }
}
