[package]
name = "indexed_slab_proc_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = { version = "1.0" }
proc-macro2 = { version = "1.0"}
proc-macro-error = { version = "1.0" }
convert_case = { version = "0.5" }

[lib]
proc-macro = true
