[package]
name = "insim_smx"
version = "0.1.0"
edition = "2021"
description = "Insim SMX file implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
bench = false
doctest = false

[dependencies]
insim_core = { path = "../insim_core" }
thiserror = "1"
