//! Definitions for the Insim packets and related bitflags, enums, etc.

mod racelaps;

mod acr;
mod axi;
mod axm;
mod axo;
mod btn;
mod cch;
mod cim;
mod cnl;
mod con;
mod cpp;
mod cpr;
mod crs;
mod csc;
mod fin;
mod flg;
mod hcp;
mod hlv;
mod iii;
mod isi;
mod ism;
mod jrr;
mod lap;
mod mal;
mod mci;
mod mode;
mod msl;
mod mso;
mod mst;
mod msx;
mod mtc;
mod nci;
mod ncn;
mod nlp;
mod npl;
mod obh;
mod oco;
mod pen;
mod pfl;
mod pit;
mod plc;
mod plh;
mod pll;
mod plp;
mod reo;
mod res;
mod rip;
mod rst;
mod scc;
mod sch;
mod sfp;
mod slc;
mod small;
mod spx;
mod ssh;
mod sta;
mod tiny;
mod toc;
mod ttc;
mod uco;
mod ver;
mod vtn;

pub use racelaps::RaceLaps;

pub use acr::{Acr, AcrResult};
pub use axi::Axi;
pub use axm::{Axm, ObjectInfo, PmoAction, PmoFlags};
pub use axo::Axo;
pub use btn::{Bfn, BfnType, Btc, Btn, BtnClickFlags, BtnInst, BtnStyleFlags, Btt};
pub use cch::{CameraView, Cch};
pub use cim::{Cim, CimMode, CimSubModeGarage, CimSubModeNormal, CimSubModeShiftU};
pub use cnl::{Cnl, CnlReason};
pub use con::{Con, ConInfo};
pub use cpp::Cpp;
pub use cpr::Cpr;
pub use crs::Crs;
pub use csc::{Csc, CscAction};
pub use fin::{Fin, RaceConfirmationFlags};
pub use flg::{Flg, FlgType};
pub use hcp::{Hcp, HcpCarHandicap};
pub use hlv::{Hlv, Hlvc};
pub use iii::Iii;
pub use isi::{Isi, IsiFlags};
pub use ism::Ism;
pub use jrr::{Jrr, JrrAction};
pub use lap::{Fuel, Fuel200, Lap};
pub use mal::Mal;
pub use mci::{CompCar, CompCarInfo, Mci};
pub use mode::Mod;
pub use msl::{Msl, SoundType};
pub use mso::{Mso, MsoUserType};
pub use mst::Mst;
pub use msx::Msx;
pub use mtc::Mtc;
pub use nci::{ILanguage, Nci};
pub use ncn::{Ncn, NcnFlags};
pub use nlp::{Nlp, NodeLapInfo};
pub use npl::{Npl, Passengers, PlayerFlags, PlayerType, SetFlags, TyreCompound};
pub use obh::{CarContact, Obh, ObhFlags};
pub use oco::{Oco, OcoAction, OcoIndex, OcoLights};
pub use pen::{Pen, PenaltyInfo, PenaltyReason};
pub use pfl::Pfl;
pub use pit::{Pit, PitLaneFact, PitStopWorkFlags, Pla, Psf};
pub use plc::{Plc, PlcAllowedCarsSet};
pub use plh::{PlayerHandicap, Plh};
pub use pll::Pll;
pub use plp::Plp;
pub use reo::Reo;
pub use res::Res;
pub use rip::{Rip, RipError, RipOptions};
pub use rst::{HostFacts, Rst};
pub use scc::Scc;
pub use sch::{Sch, SchModifiers};
pub use sfp::Sfp;
pub use slc::Slc;
pub use small::{LclFlags, LcsFlags, Small, SmallType};
pub use spx::Spx;
pub use ssh::{Ssh, SshError};
pub use sta::{RaceInProgress, Sta, StaFlags};
pub use tiny::{Tiny, TinyType};
pub use toc::Toc;
pub use ttc::{Ttc, TtcType};
pub use uco::{Uco, UcoAction};
pub use ver::Ver;
pub use vtn::{Vtn, VtnAction};
