[package]
name = "simple-outgauge"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
bytes = { workspace = true }
outgauge = { path = "../../outgauge" }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing = { workspace = true }

[lints]
workspace = true
