"""
Integration tests for the Handler + TestClient layer.

These tests run without a real LFS connection by injecting synthetic JSON
strings directly through the dispatcher.  They verify that:

- Registered handlers receive a correctly typed Pydantic model.
- Unregistered packet types are silently ignored.
- Middleware is called before handlers.
- Multiple handlers for the same type all fire, in order.
- ``wait_for`` resolves when the expected packet arrives.

Run with::

    pytest pyinsim/tests/
"""

from __future__ import annotations

import json

import pytest

# _types is auto-generated by `cargo run -p xtask-pyinsim-schema`.
# If it doesn't exist yet, run that command first.
from insim_rs._types import Mso, Ncn, Tiny
from insim_rs.handler import Handler
from insim_rs.test_client import TestClient

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

NCN_JSON = json.dumps(
    {
        "type": "Ncn",
        "reqi": 0,
        "ucid": 42,
        "uname": "testuser",
        "pname": "Test Player",
        "admin": False,
        "total": 5,
        "flags": [],
    }
)

MSO_JSON = json.dumps(
    {
        "type": "Mso",
        "reqi": 0,
        "ucid": 0,
        "plid": 0,
        "usertype": "System",
        "textstart": 0,
        "msg": "Hello, world!",
    }
)

TINY_JSON = json.dumps({"type": "Tiny", "reqi": 1, "subt": "Ping"})


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_ncn_handler_receives_typed_model() -> None:
    """Handler receives an ``Ncn`` model with correct field values."""
    handler = Handler()
    received: list[Ncn] = []

    @handler.on(Ncn)
    async def on_ncn(p: Ncn) -> None:
        received.append(p)

    tc = TestClient()
    tc.include_handler(handler)
    await tc.inject(NCN_JSON)

    assert len(received) == 1
    pkt = received[0]
    assert pkt.ucid == 42
    assert pkt.uname == "testuser"
    assert pkt.pname == "Test Player"
    assert pkt.admin is False
    assert pkt.total == 5
    assert pkt.flags == []


@pytest.mark.asyncio
async def test_mso_handler_receives_typed_model() -> None:
    """Handler receives an ``Mso`` model with correct field values."""
    handler = Handler()
    received: list[Mso] = []

    @handler.on(Mso)
    async def on_mso(p: Mso) -> None:
        received.append(p)

    tc = TestClient()
    tc.include_handler(handler)
    await tc.inject(MSO_JSON)

    assert len(received) == 1
    assert received[0].msg == "Hello, world!"
    assert received[0].usertype == "System"


@pytest.mark.asyncio
async def test_unregistered_type_is_ignored() -> None:
    """Injecting a packet type with no handler does not raise."""
    handler = Handler()
    tc = TestClient()
    tc.include_handler(handler)
    # No handler for Tiny — should be a silent no-op.
    await tc.inject(TINY_JSON)


@pytest.mark.asyncio
async def test_multiple_handlers_fire_in_order() -> None:
    """Multiple handlers for the same type are all called, in registration order."""
    handler = Handler()
    order: list[int] = []

    @handler.on(Ncn)
    async def first(_: Ncn) -> None:
        order.append(1)

    @handler.on(Ncn)
    async def second(_: Ncn) -> None:
        order.append(2)

    tc = TestClient()
    tc.include_handler(handler)
    await tc.inject(NCN_JSON)

    assert order == [1, 2]


@pytest.mark.asyncio
async def test_middleware_fires_before_handler() -> None:
    """Middleware is invoked before packet handlers."""
    calls: list[str] = []

    handler = Handler()

    @handler.on(Ncn)
    async def on_ncn(_: Ncn) -> None:
        calls.append("handler")

    tc = TestClient()

    @tc.middleware
    async def mw(packet_type: str, _packet: object) -> None:
        calls.append(f"middleware:{packet_type}")

    tc.include_handler(handler)
    await tc.inject(NCN_JSON)

    assert calls == ["middleware:Ncn", "handler"]


@pytest.mark.asyncio
async def test_multiple_handlers_all_receive_packet() -> None:
    """Packets are dispatched to every registered handler."""
    handler1, handler2 = Handler(), Handler()
    hits: list[str] = []

    @handler1.on(Ncn)
    async def h1(_: Ncn) -> None:
        hits.append("h1")

    @handler2.on(Ncn)
    async def h2(_: Ncn) -> None:
        hits.append("h2")

    tc = TestClient()
    tc.include_handler(handler1)
    tc.include_handler(handler2)
    await tc.inject(NCN_JSON)

    assert sorted(hits) == ["h1", "h2"]
