[web]
enabled = true
address = "0.0.0.0:4000"

[connection]
type = "relay"
websocket = false
auto-select-host = "Nubbins AU Demo"
connection-attempts = 0

[plugins.MyEvent]
chance = 1

[plugins.MyEvent2]
chance = 2
