name: update cache

# From GitHub docs:
#   Workflow runs can restore caches created in either the current branch or the
#   default branch (usually main).
#   If a workflow run is triggered for a pull request, it can also restore caches
#   created in the base branch.
#
# This workflow is here to refresh the cache on our "base" branch as needed.

concurrency:
  group: update-cache-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      # get the python version for the cache key
      - run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install pre-commit
          pre-commit run
